### PR TITLE
Swik 1973 exclude html

### PR DESCRIPTION
**Pull request by TBoonX**

### CODE REVIEW

**Comment by TBoonX** [comment]
CKEditor creates elements with integers as ids. Klaas mentioned that they are unique. But still we have two problems:
First the whole HTML could be changed by hand and thus duplication of ids could happen. I could fix this with detecting duplications and handle them which should be quite easy.
Second having HTML with ids in different clients could cause issues. Perhaps we could just remove them? @kadevgraaf  does CKEditor need the ids or could we remove them?

**Comment by kadevgraaf** [comment]
I have a function uniqueIDAllElements https://github.com/slidewiki/slidewiki-platform/blob/master/components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js#L556 which check if ID's are assigned -> if not generate random, and checks if ID's are duplicate -> if yes, then generate a random new one and recheck.
This is used for internal slide editor checking, and, more importantly, for the diff view/module by Ted/Todor -> to see what has changed between revisions.
This is not CKeditor stuff I recall. From what I can tell CKeditor only adds (temprorary) ID's for its own elements.

**Comment by kprist** [comment]
What I'm saying is, if the HTML provided includes any id attributes, those should be kept intact. If not, we should not introduce any new ones. The way I see it, we should simply translate everything and keep the rest intact. You could in theory use a different attribute name instead of "id", an attribute not used in HTML, something you can use for the recomposing step and then, as a final step, completely remove it from the result.

**Comment by TBoonX** [comment]
Hm then we should talk with Ted about this topic. Atm I dont see problems with adding ids if we use them anyway. Of course I could check if ids are unique and if not fix them.

Is Ted there at the hackathon in valencia? If yes we could merge it asap and improve it at the hackathon.

**Comment by kadevgraaf** [comment]
Hi @TBoonX and @kprist ! Ted is working somewhere else afaik. He might have some time to give advice, but I expect he will not be at the hackathon.
I think it is ok to add ID's, as diffing between an original and translated version of a slide will have many changes anyways - afaik adding IDs will just show that there are additions/changes which get highlighted in the diff view. 
Given this assumption/expectation, I think it is OK to merge and we can always check at the hackathon.
ID's should be unique, but checking that is always ok :)

**Comment by TBoonX** [comment]
I was now making ids unique but realized that one of my assumptions is wrong: ids could also be strings (could be edited)
Thus I have to change all ids to integers in order to handle this.
We should discuss this at the hackathon but  for now I will add making ids unique and we merge it. OK? @kadevgraaf  @kprist

**Comment by kprist** [comment]
We don't really use this service anyway so I don't have an issue with merging of course.

**Comment by kadevgraaf** [comment]
Perfect, thanks!

**Pull request merged**
